/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus.reservation.system;

import java.awt.Color;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.Date;
import java.sql.*;

/**
 *
 * @author thevi
 */
public class SeatView extends javax.swing.JFrame {

    /**
     * Creates new form SeatView
     */
    
    TicketManage tk  = new TicketManage();
    int Price = 0;
    private Connection conn;
    String[] seats = new String[4];
    String[] SeatDetail = new String[4];
    int count = 0;
    
    
    public SeatView(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jRadioButton32 = new javax.swing.JRadioButton();
        jRadioButton33 = new javax.swing.JRadioButton();
        jRadioButton34 = new javax.swing.JRadioButton();
        jRadioButton35 = new javax.swing.JRadioButton();
        jRadioButton36 = new javax.swing.JRadioButton();
        jRadioButton37 = new javax.swing.JRadioButton();
        jRadioButton38 = new javax.swing.JRadioButton();
        jRadioButton39 = new javax.swing.JRadioButton();
        jRadioButton40 = new javax.swing.JRadioButton();
        jRadioButton41 = new javax.swing.JRadioButton();
        jRadioButton42 = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                windowopend(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Seat Booking");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/reservation/system/Images/icons8-seats-64.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\thevi\\OneDrive\\Desktop\\Wallpaper\\icons8-circled-v-50.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(193, 200, 228));

        jRadioButton1.setText("A0");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/reservation/system/Images/icons8-driver-30.png"))); // NOI18N

        jRadioButton2.setText("A1");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("A2");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("A3");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton5.setText("A4");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jRadioButton6.setText("B4");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jRadioButton7.setText("B3");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jRadioButton8.setText("B2");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        jRadioButton9.setText("B1");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        jRadioButton10.setText("B0");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });

        jRadioButton11.setText("C2");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });

        jRadioButton12.setText("C1");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });

        jRadioButton13.setText("C4");
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });

        jRadioButton14.setText("C3");
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });

        jRadioButton15.setText("C0");
        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton15ActionPerformed(evt);
            }
        });

        jRadioButton16.setText("D0");
        jRadioButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton16ActionPerformed(evt);
            }
        });

        jRadioButton17.setText("D1");
        jRadioButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton17ActionPerformed(evt);
            }
        });

        jRadioButton18.setText("D2");
        jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton18ActionPerformed(evt);
            }
        });

        jRadioButton19.setText("E1");
        jRadioButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton19ActionPerformed(evt);
            }
        });

        jRadioButton20.setText("E2");
        jRadioButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton20ActionPerformed(evt);
            }
        });

        jRadioButton21.setText("E3");
        jRadioButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton21ActionPerformed(evt);
            }
        });

        jRadioButton22.setSelected(true);
        jRadioButton22.setText("E0");
        jRadioButton22.setEnabled(false);
        jRadioButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton22ActionPerformed(evt);
            }
        });

        jRadioButton23.setText("F0");
        jRadioButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton23ActionPerformed(evt);
            }
        });

        jRadioButton24.setText("F2");
        jRadioButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton24ActionPerformed(evt);
            }
        });

        jRadioButton25.setText("F3");
        jRadioButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton25ActionPerformed(evt);
            }
        });

        jRadioButton26.setText("F4");
        jRadioButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton26ActionPerformed(evt);
            }
        });

        jRadioButton27.setText("F1");
        jRadioButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton27ActionPerformed(evt);
            }
        });

        jRadioButton28.setSelected(true);
        jRadioButton28.setText("G4");
        jRadioButton28.setEnabled(false);

        jRadioButton29.setSelected(true);
        jRadioButton29.setText("G3");
        jRadioButton29.setEnabled(false);

        jRadioButton30.setText("G2");
        jRadioButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton30ActionPerformed(evt);
            }
        });

        jRadioButton31.setText("G1");
        jRadioButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton31ActionPerformed(evt);
            }
        });

        jRadioButton32.setText("G0");
        jRadioButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton32ActionPerformed(evt);
            }
        });

        jRadioButton33.setSelected(true);
        jRadioButton33.setText("H4");
        jRadioButton33.setEnabled(false);

        jRadioButton34.setSelected(true);
        jRadioButton34.setText("H3");
        jRadioButton34.setEnabled(false);

        jRadioButton35.setText("H2");
        jRadioButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton35ActionPerformed(evt);
            }
        });

        jRadioButton36.setText("H0");
        jRadioButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton36ActionPerformed(evt);
            }
        });

        jRadioButton37.setText("H1");
        jRadioButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton37ActionPerformed(evt);
            }
        });

        jRadioButton38.setSelected(true);
        jRadioButton38.setText("I4");
        jRadioButton38.setEnabled(false);
        jRadioButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton38ActionPerformed(evt);
            }
        });

        jRadioButton39.setSelected(true);
        jRadioButton39.setText("I3");
        jRadioButton39.setEnabled(false);

        jRadioButton40.setText("I2");
        jRadioButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton40ActionPerformed(evt);
            }
        });

        jRadioButton41.setText("I0");
        jRadioButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton41ActionPerformed(evt);
            }
        });

        jRadioButton42.setText("I1");
        jRadioButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton42ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("You can only select 4 seat at time");

        jButton1.setBackground(new java.awt.Color(193, 200, 228));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/reservation/system/Images/icons8-submit-for-approval-20.png"))); // NOI18N
        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(193, 200, 228));
        jButton2.setForeground(new java.awt.Color(193, 200, 228));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\thevi\\OneDrive\\Desktop\\Wallpaper\\icons8-back-24 (2).png")); // NOI18N
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\thevi\\OneDrive\\Desktop\\Wallpaper\\icons8-v-64 (2).png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(34, 34, 34))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jRadioButton23)
                                        .addComponent(jRadioButton32))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(jRadioButton31)
                                            .addGap(94, 94, 94))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jRadioButton27)
                                            .addGap(96, 96, 96)))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jRadioButton30)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jRadioButton29)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jRadioButton28))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(45, 45, 45)
                                            .addComponent(jRadioButton25)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jRadioButton26))))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jRadioButton36)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jRadioButton37))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jRadioButton41)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jRadioButton42)))
                                    .addGap(94, 94, 94)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jRadioButton40)
                                            .addGap(10, 10, 10)
                                            .addComponent(jRadioButton39)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jRadioButton38))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(jRadioButton35)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jRadioButton34)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jRadioButton33)))))
                            .addGap(6, 6, 6))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jRadioButton15)
                                        .addComponent(jRadioButton22))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRadioButton12))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jRadioButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRadioButton2)))
                            .addGap(90, 90, 90)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButton24)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jRadioButton3)
                                    .addGap(10, 10, 10)
                                    .addComponent(jRadioButton4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRadioButton5))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jRadioButton16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRadioButton17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRadioButton18))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jRadioButton11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRadioButton14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRadioButton13))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jRadioButton8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRadioButton7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRadioButton6))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jRadioButton19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRadioButton20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jRadioButton21)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jRadioButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton9)))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(75, 75, 75))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton15)
                    .addComponent(jRadioButton12)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton14)
                    .addComponent(jRadioButton13))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton16)
                    .addComponent(jRadioButton17)
                    .addComponent(jRadioButton18))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton19)
                    .addComponent(jRadioButton20)
                    .addComponent(jRadioButton21)
                    .addComponent(jRadioButton22))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton24)
                    .addComponent(jRadioButton25)
                    .addComponent(jRadioButton26)
                    .addComponent(jRadioButton23)
                    .addComponent(jRadioButton27))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton30)
                    .addComponent(jRadioButton29)
                    .addComponent(jRadioButton28)
                    .addComponent(jRadioButton32)
                    .addComponent(jRadioButton31))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton35)
                    .addComponent(jRadioButton34)
                    .addComponent(jRadioButton33)
                    .addComponent(jRadioButton36)
                    .addComponent(jRadioButton37))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton40)
                    .addComponent(jRadioButton39)
                    .addComponent(jRadioButton38)
                    .addComponent(jRadioButton41)
                    .addComponent(jRadioButton42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jButton1)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton1";
            jRadioButton1.setForeground(Color.blue);
            jRadioButton1.setEnabled(false);
            seats[count]  = jRadioButton1.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton3";
            jRadioButton3.setForeground(Color.blue);
            jRadioButton3.setEnabled(false);
            seats[count]  = jRadioButton3.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton8";
            jRadioButton8.setForeground(Color.blue);
            jRadioButton8.setEnabled(false);
            seats[count]  = jRadioButton8.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton10";
            jRadioButton10.setForeground(Color.blue);
            jRadioButton10.setEnabled(false);
            seats[count]  = jRadioButton10.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton11";
            jRadioButton11.setForeground(Color.blue);
            jRadioButton11.setEnabled(false);
            seats[count]  = jRadioButton11.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton15ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton15";
            jRadioButton15.setForeground(Color.blue);
            jRadioButton15.setEnabled(false);
            seats[count]  = jRadioButton15.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton15ActionPerformed

    private void jRadioButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton16ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton16";
            jRadioButton16.setForeground(Color.blue);
            jRadioButton16.setEnabled(false);
            seats[count]  = jRadioButton16.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton16ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton9";
            jRadioButton9.setForeground(Color.blue);
            jRadioButton9.setEnabled(false);
            seats[count]  = jRadioButton9.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton19ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton19";
            jRadioButton19.setForeground(Color.blue);
            jRadioButton19.setEnabled(false);
            seats[count]  = jRadioButton19.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton19ActionPerformed

    private void jRadioButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton22ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton22";
            jRadioButton22.setForeground(Color.blue);
            jRadioButton22.setEnabled(false);
            seats[count]  = jRadioButton22.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton22ActionPerformed

    private void jRadioButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton23ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton23";
            jRadioButton23.setForeground(Color.blue);
            jRadioButton23.setEnabled(false);
            seats[count]  = jRadioButton23.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton23ActionPerformed

    private void jRadioButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton24ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton24";
            jRadioButton24.setForeground(Color.blue);
            jRadioButton24.setEnabled(false);
            seats[count]  = jRadioButton24.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton24ActionPerformed

    private void jRadioButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton27ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton27";
            jRadioButton27.setForeground(Color.blue);
            jRadioButton27.setEnabled(false);
            seats[count]  = jRadioButton27.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton27ActionPerformed

    private void jRadioButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton30ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton30";
            jRadioButton30.setForeground(Color.blue);
            jRadioButton30.setEnabled(false);
            seats[count]  = jRadioButton30.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton30ActionPerformed

    private void jRadioButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton31ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton31";
            jRadioButton31.setForeground(Color.blue);
            jRadioButton31.setEnabled(false);
            seats[count]  = jRadioButton31.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton31ActionPerformed

    private void jRadioButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton32ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton32";
            jRadioButton32.setForeground(Color.blue);
            jRadioButton32.setEnabled(false);
            seats[count]  = jRadioButton32.getText();
            Price = Price+100;count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton32ActionPerformed

    private void jRadioButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton35ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton35";
            jRadioButton35.setForeground(Color.blue);
            jRadioButton35.setEnabled(false);
            seats[count]  = jRadioButton35.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton35ActionPerformed

    private void jRadioButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton36ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton36";
            jRadioButton36.setForeground(Color.blue);
            jRadioButton36.setEnabled(false);
            seats[count]  = jRadioButton36.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton36ActionPerformed

    private void jRadioButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton37ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton37";
            jRadioButton37.setForeground(Color.blue);
            jRadioButton37.setEnabled(false);
            seats[count]  = jRadioButton37.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton37ActionPerformed

    private void jRadioButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton40ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton40";
            jRadioButton40.setForeground(Color.blue);
            jRadioButton40.setEnabled(false);
            seats[count]  = jRadioButton40.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton40ActionPerformed

    private void jRadioButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton41ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton41";
            jRadioButton41.setForeground(Color.blue);
            jRadioButton41.setEnabled(false);
            seats[count]  = jRadioButton41.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton41ActionPerformed

    private void jRadioButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton42ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton42";
            jRadioButton42.setForeground(Color.blue);
            jRadioButton42.setEnabled(false);
            seats[count]  = jRadioButton42.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton42ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton2";
            jRadioButton2.setForeground(Color.blue);
            jRadioButton2.setEnabled(false);
            seats[count]  = jRadioButton2.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        System.out.println(count);
        if(count<4){
            SeatDetail[count] = "jRadioButton4";
            jRadioButton4.setForeground(Color.blue);
            jRadioButton4.setEnabled(false);
            seats[count]  = jRadioButton4.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);   
        }
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton5";
            jRadioButton5.setForeground(Color.blue);
            jRadioButton5.setEnabled(false);
            seats[count]  = jRadioButton5.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        if(count<4){
            SeatDetail[count] = "jRadioButton7";
            jRadioButton7.setForeground(Color.blue);
            jRadioButton7.setEnabled(false);
            seats[count]  = jRadioButton7.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        if(count<4){
            SeatDetail[count] = "jRadioButton6";
            jRadioButton6.setForeground(Color.blue);
            jRadioButton6.setEnabled(false);
            seats[count]  = jRadioButton6.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void TempAdd()
    {
        try{
            String sql = "INSERT INTO temp_detail VALUES(?,?,?,?)"; //SeatNo(Varchar)(uniq),BusNo(Varchar),Date (Varchar),SeatTag

            AllStore as = new AllStore();
            Date date1 = as.getDate();
            java.sql.Date sDate= new java.sql.Date(date1.getTime());
            Connection conn = tk.conn;
            for(int j=0;j<count;j++)
            {
                PreparedStatement stm = conn.prepareStatement(sql);

                stm.setString(1,seats[j]);
                stm.setString(2, "Bus-A0010");
                stm.setDate(3, sDate); 
                stm.setString(4, SeatDetail[j]);
                stm.executeUpdate();
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Confirmation c = new Confirmation();
        c.setVisible(true);
        String LabData = "";
        for(int j=0;j<seats.length;j++)
        {
            LabData = LabData+" "+ seats[j];        
        }
        c.seatLabel.setText(LabData);
        String price = String.valueOf(Price);
        c.priceLabel.setText(price);
        TempAdd();
        this.setVisible(false); 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void windowopend(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowopend
        // TODO add your handling code here:        
        Database_Check();
    }//GEN-LAST:event_windowopend

    private void jRadioButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton38ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton12";
            jRadioButton12.setForeground(Color.blue);
            jRadioButton12.setEnabled(false);
            seats[count]  = jRadioButton12.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton14";
            jRadioButton14.setForeground(Color.blue);
            jRadioButton14.setEnabled(false);
            seats[count]  = jRadioButton14.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton14ActionPerformed

    private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton13";
            jRadioButton13.setForeground(Color.blue);
            jRadioButton13.setEnabled(false);
            seats[count]  = jRadioButton13.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton13ActionPerformed

    private void jRadioButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton17ActionPerformed
        // TODO add your handling code here:
        if(count<4){
            SeatDetail[count] = "jRadioButton17";
            jRadioButton17.setForeground(Color.blue);
            jRadioButton17.setEnabled(false);
            seats[count]  = jRadioButton17.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jRadioButton17ActionPerformed

    private void jRadioButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton18ActionPerformed

        if(count<4){
            SeatDetail[count] = "jRadioButton18";
            jRadioButton18.setForeground(Color.blue);
            jRadioButton18.setEnabled(false);
            seats[count]  = jRadioButton18.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton18ActionPerformed

    private void jRadioButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton20ActionPerformed
        if(count<4){
            SeatDetail[count] = "jRadioButton20";
            jRadioButton20.setForeground(Color.blue);
            jRadioButton20.setEnabled(false);
            seats[count]  = jRadioButton20.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton20ActionPerformed

    private void jRadioButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton21ActionPerformed
        if(count<4){
            SeatDetail[count] = "jRadioButton21";
            jRadioButton21.setForeground(Color.blue);
            jRadioButton21.setEnabled(false);
            seats[count]  = jRadioButton21.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton21ActionPerformed

    private void jRadioButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton25ActionPerformed
        if(count<4){
            SeatDetail[count] = "jRadioButton25";
            jRadioButton25.setForeground(Color.blue);
            jRadioButton25.setEnabled(false);
            seats[count]  = jRadioButton25.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton25ActionPerformed

    private void jRadioButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton26ActionPerformed
        if(count<4){
            SeatDetail[count] = "jRadioButton26";
            jRadioButton26.setForeground(Color.blue);
            jRadioButton26.setEnabled(false);
            seats[count]  = jRadioButton26.getText();
            Price = Price+100;
            count = count+1;
        }
        else{
            JOptionPane.showMessageDialog(null, "You Reached Maximum Seat Selection Limit", "Alert",JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton26ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        SeatBooking sk = new SeatBooking();
        sk.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Database_Check(){
        try{        
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/Demo_Bus","root","");
            String sql = "SELECT SeatTag FROM booked_seat";
            PreparedStatement stm = conn.prepareStatement(sql);
            ResultSet rst = stm.executeQuery();
            
            while (rst.next()){            
                String booked_seat1= rst.getString(1);
                
                if(booked_seat1.contains("jRadioButton1"))
                {
                    jRadioButton1.setEnabled(false);
                }
                if(booked_seat1.contains("jRadioButton2"))
                {
                    jRadioButton2.setEnabled(false);
                }
                if(booked_seat1.contains("jRadioButton3"))
                {
                    jRadioButton3.setEnabled(false);
                }
                if(booked_seat1.contains("jRadioButton4"))
                {
                    jRadioButton4.setEnabled(false);
                }                
                if(booked_seat1.contains("jRadioButton5")){ 
                    jRadioButton5.setEnabled(false);}

                if(booked_seat1.contains("jRadioButton6")){ 
                    jRadioButton6.setEnabled(false);}

                if(booked_seat1.contains("jRadioButton7")){ 
                    jRadioButton7.setEnabled(false);}

                if(booked_seat1.contains("jRadioButton8")){ 
                    jRadioButton8.setEnabled(false);}

                if(booked_seat1.contains("jRadioButton9")){ 
                    jRadioButton9.setEnabled(false);}

                if(booked_seat1.contains("jRadioButton10")){
                     jRadioButton10.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton11")){
                     jRadioButton11.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton12")){
                     jRadioButton12.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton13")){
                     jRadioButton13.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton14")){
                     jRadioButton14.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton15")){
                     jRadioButton15.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton16")){
                     jRadioButton16.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton17")){
                     jRadioButton17.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton18")){
                     jRadioButton18.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton19")){
                     jRadioButton19.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton20")){
                     jRadioButton20.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton21")){
                     jRadioButton21.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton22")){
                     jRadioButton22.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton23")){
                     jRadioButton23.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton24")){
                     jRadioButton24.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton25")){
                     jRadioButton25.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton26")){
                     jRadioButton26.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton27")){
                     jRadioButton27.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton31")){
                     jRadioButton31.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton32")){
                     jRadioButton32.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton30")){
                     jRadioButton30.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton36")){
                     jRadioButton36.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton37")){
                     jRadioButton37.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton35")){
                     jRadioButton35.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton41")){
                     jRadioButton41.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton42")){
                     jRadioButton42.setEnabled(false);
                     }
                if(booked_seat1.contains("jRadioButton40")){
                     jRadioButton40.setEnabled(false);
                     }
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeatView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeatView().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton32;
    private javax.swing.JRadioButton jRadioButton33;
    private javax.swing.JRadioButton jRadioButton34;
    private javax.swing.JRadioButton jRadioButton35;
    private javax.swing.JRadioButton jRadioButton36;
    private javax.swing.JRadioButton jRadioButton37;
    private javax.swing.JRadioButton jRadioButton38;
    private javax.swing.JRadioButton jRadioButton39;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton40;
    private javax.swing.JRadioButton jRadioButton41;
    private javax.swing.JRadioButton jRadioButton42;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
